# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_29; end
module ::Anonymous_Delegator_8; end
module ActionDispatch::Response::ContentTypeHeader; end
module Rails::Application::Configuration; end
